# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  pull_request:
      branches: [ "QA" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
          
    - name: Compilar o Java
      run: javac -cp src src/Main.java

    - name: Executando o Teste
      run: java -cp src src/Teste.java

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: henriqu33bbr/simuladodevops
        
        tags: v1.${{ github.run_number }}, latest
        registry: docker.io
        dockerfile: dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
